import marimo

__generated_with = "0.10.11"
app = marimo.App(width="medium")


@app.cell
def _(mo):
    mo.md("""# Rachel's Multiple Choice Question Plugin""")
    return


@app.cell
def _():
    import marimo as mo
    import anywidget
    import traitlets
    return anywidget, mo, traitlets


@app.cell
def _(anywidget, traitlets):
    class MultipleChoiceQuestion(anywidget.AnyWidget):
        _esm = "mcq.js"
        _css = "mcq.css"
        questions = traitlets.Dict({}, help="A set of question and answer options").tag(sync=True)
        _selected_options = traitlets.List([]).tag(sync=True)
    return (MultipleChoiceQuestion,)


@app.cell
def _(MultipleChoiceQuestion):
    # Data Generated by ChatGPT & Stored in the separate folder
    # Enhancement Idea: call OpenAI API
    import json

    with open('./mcq-data/data1.json') as f:
        d = json.load(f)

    MultipleChoiceQuestion(questions=d)
    return d, f, json


if __name__ == "__main__":
    app.run()
