# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Run plugin tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install uv
      run: |
        pip install uv
    - name: Set up virtual environment
      run: |
        uv venv
        source .venv/bin/activate
        echo PATH=$PATH >> $GITHUB_ENV
    - name: Install dependencies
      run: |
        uv pip install -r pyproject.toml
        if [ -f requirements.txt ]; then uv pip install -r requirements.txt; fi
      shell: bash
    - name: Install testing dependencies
      run: |
        cd tests
        uv pip install -r requirements.txt
        cd ..
    - name: Test with pytest
      run: |
        pytest
